// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission8_Assignment.Models;

#nullable disable

namespace Mission8_Assignment.Migrations
{
    [DbContext(typeof(QuadrantContext))]
    [Migration("20260223213054_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Mission8_Assignment.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Work"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Personal"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Health"
                        });
                });

            modelBuilder.Entity("Mission8_Assignment.Models.Quadrant", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("dueDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Quadrants");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            CategoryId = 1,
                            completed = false,
                            dueDate = "2026-03-01",
                            quadrant = 1,
                            task = "Finish report"
                        },
                        new
                        {
                            TaskId = 2,
                            CategoryId = 3,
                            completed = false,
                            dueDate = "2026-03-05",
                            quadrant = 2,
                            task = "Call doctor"
                        },
                        new
                        {
                            TaskId = 3,
                            CategoryId = 2,
                            completed = true,
                            dueDate = "2026-02-25",
                            quadrant = 3,
                            task = "Buy groceries"
                        });
                });

            modelBuilder.Entity("Mission8_Assignment.Models.Quadrant", b =>
                {
                    b.HasOne("Mission8_Assignment.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
